---
title: "Scaleup Analysis"
author: "Andres Calderon"
date: '`r Sys.Date()`'
output:
  html_document: default
  pdf_document: default
---

<!---  --->

### 1024 Partitions.

```{r ScaleupSetup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, data.table, foreach, sqldf, tidyr)

PATH = "Y3Q1/Scripts/Scaleup/Scaleup_2017-10-18-14-53/"
filename ="Berlin_N20K-80K_E10.0-50.0"
PHD_HOME = Sys.getenv(c("PHD_HOME"))

files = system(paste0("ls ",PHD_HOME,PATH,filename,"_C*.csv"), intern = T)
data = data.frame()
foreach(f = files) %do% {
  data = rbind(data, read.csv(f, header = F))
}
data = data[, c(2, 3, 6, 9)]
names(data) = c("Epsilon", "Dataset", "Time", "Cores")
data20 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '20K'")
data40 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '40K'")
data60 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '60K'")
data80 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '80K'")
data = rbind(data20, data40, data60, data80)
data = sqldf("SELECT Epsilon, Dataset, Cores, AVG(Time) AS Time FROM data GROUP BY 1, 2, 3")
data$Dataset = factor(data$Dataset, levels = paste0(seq(20, 80, 20), "K"))
data$Cores = factor(data$Cores)
```

```{r ScaleupPlot, echo=FALSE, fig.width=10.5, fig.height=7.5, fig.align='center'}
temp_title = paste("(radius of disk in mts) in Berlin dataset (Partitions = 1024).")
title = substitute(paste("Scaleup by ", epsilon) ~ temp_title, list(temp_title = temp_title))
g = ggplot(data=data, aes(x=factor(Epsilon), y=Time, fill=Dataset)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75),width = 0.75) +
  labs(title=title, y="Time(s)", x=expression(paste(epsilon,"(mts)")))
plot(g)
```

### 1536 Partitions.

```{r ScaleupSetup2, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, data.table, foreach, sqldf, tidyr)

PATH = "Y3Q1/Scripts/Scaleup/Scaleup_2017-10-18-18-06/"
filename ="Berlin_N20K-80K_E10.0-50.0"
PHD_HOME = Sys.getenv(c("PHD_HOME"))

files = system(paste0("ls ",PHD_HOME,PATH,filename,"_C*.csv"), intern = T)
data = data.frame()
foreach(f = files) %do% {
  data = rbind(data, read.csv(f, header = F))
}
data = data[, c(2, 3, 6, 9)]
names(data) = c("Epsilon", "Dataset", "Time", "Cores")
data20 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '20K'")
data40 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '40K'")
data60 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '60K'")
data80 = sqldf("SELECT Epsilon, Dataset, Cores, Time FROM data WHERE Dataset LIKE '80K'")
data = rbind(data20, data40, data60, data80)
data = sqldf("SELECT Epsilon, Dataset, Cores, AVG(Time) AS Time FROM data GROUP BY 1, 2, 3")
data$Dataset = factor(data$Dataset, levels = paste0(seq(20, 80, 20), "K"))
data$Cores = factor(data$Cores)
```

```{r ScaleupPlot2, echo=FALSE, fig.width=10.5, fig.height=7.5, fig.align='center'}
temp_title = paste("(radius of disk in mts) in Berlin dataset (Partitions = 1536).")
title = substitute(paste("Scaleup by ", epsilon) ~ temp_title, list(temp_title = temp_title))
g = ggplot(data=data, aes(x=factor(Epsilon), y=Time, fill=Dataset)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75),width = 0.75) +
  labs(title=title, y="Time(s)", x=expression(paste(epsilon,"(mts)")))
plot(g)
```
