---
title: "Scaleup Analysis"
author: "Andres Calderon"
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: 
    theme: paper
params:
  phd_path:
    value: "Y3Q1/Scripts/Scaleup/"
  filename:
    value: "nohup"
  extension:
    value: "out"
---

<!--- Reading data... --->

```{r ScaleupSetup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, data.table, foreach, sqldf, tidyr, stringr, dplyr)
options(digits = 15)
source('analyzeNohupLog.R')

PHD_HOME = Sys.getenv(c("PHD_HOME"))
PHD_PATH = params$phd_path
FILENAME = params$filename
EXTENSION = params$extension

runRandomTesterRunnerETL(PHD_HOME, PHD_PATH,FILENAME,EXTENSION)
data0 = read.csv(paste0(PHD_HOME,PHD_PATH,FILENAME,".csv"))

data1 = sqldf("SELECT Stage, Epsilon, Cores, avg(Time) AS Time FROM data0 GROUP BY 1, 2, 3")
data1$Cores = factor(data1$Cores)
```

## `r FILENAME`

```{r ScaleupPlot, echo=FALSE, fig.width=10.5, fig.height=7.5, fig.align='center'}
temp_title = paste("(radius of disk in mts) in Berlin dataset.")
title = substitute(paste("Execution time by ", epsilon) ~ temp_title, list(temp_title = temp_title))
g = ggplot(data=data1, aes(x=factor(Epsilon), y=Time, fill=Cores)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75),width = 0.75) +
  labs(title=title, y="Time(s)", x=expression(paste(epsilon,"(mts)"))) +
  facet_wrap(~Stage)
plot(g)
```
