## Get a small file...
head -c 5000000 text8 > text8_small 
## Build the model...
./word2vec -train text8_small -output vectors_small.bin -cbow 1 -size 100 -window 5 -negative 0 -hs 25 -threads 1 -iter 4 -min-count 2 -binary 1 
## Query word distances...
./distance vectors_small.bin 
