a = c(0.63, 0.33, 0.33, 0.40, 0.41, 0.5)
b = c(74.2, 23.3, 32.7, 25.0, 6.0, 50)

y = as.matrix(read.table('Temp/k1_cancer.dat'))
x = seq(0.01,1,length.out = length(y))
#pdf("figures/cancer.pdf", 7.83, 5.17)
plot(x,y,type='l',col='red',lwd=2,xlab="p",ylab="Error rate")
lines(x,(1-a[1])*exp(b[1]*(x-1))+c,col='blue',lwd=2,lty=2)
legend('topleft', legend=c("observed error", "fit model"),inset=c(0.01,0.02)
       ,col=c(2,4),lty=c(1,2),lwd=c(2,2),cex=0.9)
#dev.off()

y = as.matrix(read.table('Temp/k1_iris.dat'))
#pdf("figures/iris.pdf", 7.83, 5.17)
plot(x,y,type='l',col='red',lwd=2,xlab="p",ylab="Error rate")
lines(x,(1-a[2])*exp(b[2]*(x-1))+c,col='blue',lwd=2,lty=2)
legend('topleft', legend=c("observed error", "fit model"),inset=c(0.01,0.02)
       ,col=c(2,4),lty=c(1,2),lwd=c(2,2),cex=0.9)
#dev.off()

y = as.matrix(read.table('Temp/k1_seeds.dat'))
#pdf("figures/seeds.pdf", 7.83, 5.17)
plot(x,y,type='l',col='red',lwd=2,xlab="p",ylab="Error rate")
lines(x,(1-a[3])*exp(b[3]*(x-1))+c,col='blue',lwd=2,lty=2)
legend('topleft', legend=c("observed error", "fit model"),inset=c(0.01,0.02)
       ,col=c(2,4),lty=c(1,2),lwd=c(2,2),cex=0.9)
#dev.off()

y = as.matrix(read.table('Temp/k1_wine.dat'))
#pdf("figures/wine.pdf", 7.83, 5.17)
plot(x,y,type='l',col='red',lwd=2,xlab="p",ylab="Error rate")
lines(x,(1-a[4])*exp(b[4]*(x-1))+c,col='blue',lwd=2,lty=2)
legend('topleft', legend=c("observed error", "fit model"),inset=c(0.01,0.02)
       ,col=c(2,4),lty=c(1,2),lwd=c(2,2),cex=0.9)
#dev.off()

y = as.matrix(read.table('Temp/k1_zoo.dat'))
#pdf("figures/zoo.pdf", 7.83, 5.17)
plot(x,y,type='l',col='red',lwd=2,xlab="p",ylab="Error rate")
lines(x,(1-a[5])*exp(b[5]*(x-1))+c,col='blue',lwd=2,lty=2)
legend('topleft', legend=c("observed error", "fit model"),inset=c(0.01,0.02)
       ,col=c(2,4),lty=c(1,2),lwd=c(2,2),cex=0.9)
#dev.off()

y = as.matrix(read.table('Temp/k1_banknote.dat'))
#pdf("figures/zoo.pdf", 7.83, 5.17)
plot(x,y,type='l',col='red',lwd=2,xlab="p",ylab="Error rate")
lines(x,(1-a[6])*exp(b[6]*(x-1))+c,col='blue',lwd=2,lty=2)
legend('topleft', legend=c("observed error", "fit model"),inset=c(0.01,0.02)
       ,col=c(2,4),lty=c(1,2),lwd=c(2,2),cex=0.9)
#dev.off()
